// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from './.open-next/worker.js';

type WorkerEnv = CloudflareEnv & {
  NEXTAUTH_URL?: string;
  NEXT_PUBLIC_APP_URL?: string;
  CRON_SECRET?: string;
  PROCESS_WORKER_SECRET?: string;
  NEXTAUTH_SECRET?: string;
  AUTH_SECRET?: string;
  DEPLOYMENT_STAGE?: string;
  ENABLE_CRON?: string;
};

function resolveAppOrigin(env: WorkerEnv): string {
  return (env.NEXTAUTH_URL || env.NEXT_PUBLIC_APP_URL || 'https://podsum.cc').replace(/\/+$/, '');
}

function resolveCronTarget(cron: string): string {
  if (cron === '0 4 * * *') {
    return '/api/worker/alignment-backfill';
  }
  return '/api/worker/process';
}

function isCronEnabled(env: WorkerEnv): boolean {
  return env.ENABLE_CRON === 'true' || env.DEPLOYMENT_STAGE === 'production';
}

function buildCronHeaders(env: WorkerEnv): Headers {
  const headers = new Headers({ 'Content-Type': 'application/json' });
  const cronSecret = env.CRON_SECRET?.trim();
  const workerSecret =
    env.PROCESS_WORKER_SECRET?.trim() || env.NEXTAUTH_SECRET?.trim() || env.AUTH_SECRET?.trim();

  if (cronSecret) {
    headers.set('Authorization', `Bearer ${cronSecret}`);
  }
  if (workerSecret) {
    headers.set('x-worker-secret', workerSecret);
  }

  return headers;
}

async function invokeCronRoute(event: ScheduledController, env: WorkerEnv, ctx: ExecutionContext): Promise<void> {
  const targetUrl = `${resolveAppOrigin(env)}${resolveCronTarget(event.cron)}`;
  const response = await handler.fetch(
    new Request(targetUrl, {
      method: 'POST',
      headers: buildCronHeaders(env),
      body: JSON.stringify({
        source: 'cloudflare-cron',
        cron: event.cron,
        scheduledTime: event.scheduledTime,
      }),
    }),
    env,
    ctx,
  );

  if (!response.ok) {
    const errorText = await response.text().catch(() => '');
    throw new Error(`Scheduled route ${targetUrl} failed with ${response.status}: ${errorText}`);
  }
}

export default {
  fetch: handler.fetch,

  async scheduled(event, env, ctx) {
    if (!isCronEnabled(env as WorkerEnv)) {
      console.log(`Skipping scheduled event ${event.cron}; cron is disabled for this deployment.`);
      return;
    }
    ctx.waitUntil(invokeCronRoute(event, env as WorkerEnv, ctx));
  },
} satisfies ExportedHandler<WorkerEnv>;
