// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/signin" | "/auth/signup" | "/dashboard/[id]" | "/my" | "/ops/extension-monitor" | "/public-podcast-summary" | "/upload"
type AppRouteHandlerRoutes = "/api/analysis/[id]" | "/api/auth-status" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/db-init" | "/api/db-test" | "/api/debug" | "/api/debug/env" | "/api/delete-user" | "/api/extension/auth/login" | "/api/extension/monitor-event" | "/api/extension/status/[id]" | "/api/extension/transcribe-status/[jobId]" | "/api/extension/upload-audio" | "/api/extension/upload-srt" | "/api/extension/upload-youtube" | "/api/list-users" | "/api/ops/extension-monitor/tasks" | "/api/ops/extension-monitor/tasks/[id]" | "/api/podcasts" | "/api/podcasts/[id]" | "/api/process" | "/api/process/enqueue" | "/api/qa/[id]" | "/api/test-login" | "/api/upload" | "/api/worker/process"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/analysis/[id]": { "id": string; }
  "/api/auth-status": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/db-init": {}
  "/api/db-test": {}
  "/api/debug": {}
  "/api/debug/env": {}
  "/api/delete-user": {}
  "/api/extension/auth/login": {}
  "/api/extension/monitor-event": {}
  "/api/extension/status/[id]": { "id": string; }
  "/api/extension/transcribe-status/[jobId]": { "jobId": string; }
  "/api/extension/upload-audio": {}
  "/api/extension/upload-srt": {}
  "/api/extension/upload-youtube": {}
  "/api/list-users": {}
  "/api/ops/extension-monitor/tasks": {}
  "/api/ops/extension-monitor/tasks/[id]": { "id": string; }
  "/api/podcasts": {}
  "/api/podcasts/[id]": { "id": string; }
  "/api/process": {}
  "/api/process/enqueue": {}
  "/api/qa/[id]": { "id": string; }
  "/api/test-login": {}
  "/api/upload": {}
  "/api/worker/process": {}
  "/auth/signin": {}
  "/auth/signup": {}
  "/dashboard/[id]": { "id": string; }
  "/my": {}
  "/ops/extension-monitor": {}
  "/public-podcast-summary": {}
  "/upload": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
