// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/my/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my">> = Specific
  const handler = {} as typeof import("../../app/my/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ops/extension-monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ops/extension-monitor">> = Specific
  const handler = {} as typeof import("../../app/ops/extension-monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/public-podcast-summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public-podcast-summary">> = Specific
  const handler = {} as typeof import("../../app/public-podcast-summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/upload">> = Specific
  const handler = {} as typeof import("../../app/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analysis/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analysis/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/analysis/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth-status">> = Specific
  const handler = {} as typeof import("../../app/api/auth-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/db-init/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/db-init">> = Specific
  const handler = {} as typeof import("../../app/api/db-init/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/db-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/db-test">> = Specific
  const handler = {} as typeof import("../../app/api/db-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/env">> = Specific
  const handler = {} as typeof import("../../app/api/debug/env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug">> = Specific
  const handler = {} as typeof import("../../app/api/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/delete-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/delete-user">> = Specific
  const handler = {} as typeof import("../../app/api/delete-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/extension/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension/monitor-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension/monitor-event">> = Specific
  const handler = {} as typeof import("../../app/api/extension/monitor-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension/status/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension/status/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/extension/status/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension/transcribe-status/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension/transcribe-status/[jobId]">> = Specific
  const handler = {} as typeof import("../../app/api/extension/transcribe-status/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension/upload-audio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension/upload-audio">> = Specific
  const handler = {} as typeof import("../../app/api/extension/upload-audio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension/upload-srt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension/upload-srt">> = Specific
  const handler = {} as typeof import("../../app/api/extension/upload-srt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension/upload-youtube/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension/upload-youtube">> = Specific
  const handler = {} as typeof import("../../app/api/extension/upload-youtube/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/list-users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/list-users">> = Specific
  const handler = {} as typeof import("../../app/api/list-users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ops/extension-monitor/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ops/extension-monitor/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/ops/extension-monitor/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ops/extension-monitor/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ops/extension-monitor/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/ops/extension-monitor/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/podcasts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/podcasts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/podcasts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/podcasts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/podcasts">> = Specific
  const handler = {} as typeof import("../../app/api/podcasts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/process/enqueue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/process/enqueue">> = Specific
  const handler = {} as typeof import("../../app/api/process/enqueue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/process">> = Specific
  const handler = {} as typeof import("../../app/api/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/qa/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qa/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/qa/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-login">> = Specific
  const handler = {} as typeof import("../../app/api/test-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/worker/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/worker/process">> = Specific
  const handler = {} as typeof import("../../app/api/worker/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
